name: Latest Youtube Videos
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-youtube-videos:
    name: Update this repo's README with latest youtube videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "VIDEO-LIST"
          commit_message: "Updated readme with the latest youtube video"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC4G--03ELkOXX-dcSq_LMQQ"
